name: flutter_web.examples.gallery

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  intl: ^0.15.7

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  flutter_web_test: any
  test: ^1.0.0

dependency_overrides:
  flutter_web:
    path: ../../packages/flutter_web
  flutter_web_test:
    path: ../../packages/flutter_web_test
  flutter_web_ui:
    path: ../../packages/flutter_web_ui
